name: Create PR
on:
  push:
    branches-ignore: main
jobs:
  action-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: main
          draft: true
        id: create-pr
      - run: gh pr merge --merge --auto "${{ steps.create-pr.outputs.pr_number }}"
        env:
          GH_TOKEN: ${{ github.token }}
