name: Create PR
on:
  push:
    branches-ignore: main
jobs:
  action-pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: wagoid/commitlint-github-action@v5
        id: commitlint

      - run: echo ${{ steps.commitlint.outputs }}
      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: main
          draft: ${{ steps.commitlint.outputs.results.length > 0 }}
        id: create-pr

      - run: gh pr merge --rebase --auto "${{ steps.create-pr.outputs.pr_number }}"
        env:
          GH_TOKEN: ${{ github.token }}
        continue-on-error: true

