name: Initialize

on: push

jobs:
  initialize:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 21
      - run: git pull
      - run: echo "${{ github.repository }}"

      - name: Run replace-all-words
        run: npx replace-all-words ./ template-typescript ${{ github.repository }} && rm .github/workflows/initialize.yml
        if: github.repository != 'template-typescript'
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'autogen: replace template with repository name and remove initialize / npx replace-all-words ./ template-typescript ${{ github.repository }} && rm .github/workflows/initialize.yml'
